/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contextUpgradeableSol from"./ContextUpgradeable.sol/index.js";
export type { contextUpgradeableSol };
