/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from"./contracts/index.js";
export type { contracts };
import type * as contractsUpgradeableV5 from"./contracts-upgradeable-v5/index.js";
export type { contractsUpgradeableV5 };
import type * as contractsV5 from"./contracts-v5/index.js";
export type { contractsV5 };
