/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as automationBaseSol from"./AutomationBase.sol/index.js";
export type { automationBaseSol };
import type * as automationCompatibleSol from"./AutomationCompatible.sol/index.js";
export type { automationCompatibleSol };
import type * as interfaces from"./interfaces/index.js";
export type { interfaces };
