/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as automationCompatibleInterfaceSol from"./AutomationCompatibleInterface.sol/index.js";
export type { automationCompatibleInterfaceSol };
