/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as automationBaseSol from "./AutomationBase.sol/index.js";
export * as automationCompatibleSol from "./AutomationCompatible.sol/index.js";
export * as interfaces from "./interfaces/index.js";
