/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iFunctionsClientSol from "./IFunctionsClient.sol/index.js";
export * as iFunctionsRouterSol from "./IFunctionsRouter.sol/index.js";
