/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ownableUpgradeableSol from"./OwnableUpgradeable.sol/index.js";
export type { ownableUpgradeableSol };
