/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as functionsRequestSol from"./FunctionsRequest.sol/index.js";
export type { functionsRequestSol };
