/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iFunctionsClientSol from"./IFunctionsClient.sol/index.js";
export type { iFunctionsClientSol };
import type * as iFunctionsRouterSol from"./IFunctionsRouter.sol/index.js";
export type { iFunctionsRouterSol };
