/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agtFeedSol from"./AGTFeed.sol/index.js";
export type { agtFeedSol };
import type * as agtReserveFeedSol from"./AGTReserveFeed.sol/index.js";
export type { agtReserveFeedSol };
import type * as arwFeedSol from"./ARWFeed.sol/index.js";
export type { arwFeedSol };
import type * as baseFunctionsConsumerSol from"./BaseFunctionsConsumer.sol/index.js";
export type { baseFunctionsConsumerSol };
import type * as functionsClientSol from"./FunctionsClient.sol/index.js";
export type { functionsClientSol };
